### PR TITLE
Add ship images next to their name and fix colors in stat columns

### PR DESCRIPTION
**Pull request by KonatoK**

### CODE REVIEW

**Comment by KagamiChan** [comment]
This is an awesome idea, but I'm afraid it could not be landed because 
- the plugin bundle size becomes huge, users have to download more data
- there'll be much labour to keep these avatars up to date, and we'll be forced to update the plugin every time new ships come out

**Comment by KagamiChan** [comment]
I picked the switching color commit

**Comment by KonatoK** [comment]
It's just 3 MB at most and the images could be reduced in dimensions and further compressed to achieve a smaller file size.

I kinda agree with new ships, but it's not like we get new ships every day, and possibly adding a default image in case the ship can't be found could make things better

**Comment by KagamiChan** [comment]
@KonatoK We're looking into possibilities of automatic swf extraction to spare us some time for a cup of coffee :)

**Pull request closed without merging**
