### PR TITLE
Fix the display problem of properties that can be strengthened

### PR DESCRIPTION
**Pull request by zhuzhe1995**
Modifications:
Change some variables' Names.
Set the value behind '/' to the remained value that you can strengthen.

### CODE REVIEW

**Comment by myzWILLmake** [comment]
It is wrong because the value of xxxNow contains the value of equipment's strengthening.

**Comment by myzWILLmake** [comment]
It is unclear if you do this and still use the "+" sign.

**Comment by myzWILLmake** [comment]
I will adjust it in the next version.

**Comment by magicae** [comment]
I think this pr is ok. kcv also set the value behind '/' to the remained value that you can strengthen and it might be more useful.

**Comment by myzWILLmake** [comment]
I got it.

**Pull request closed without merging**
